blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogUpdateView, BlogDetailView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path("blogs_list", cache_page(60)(BlogListView.as_view()), name="blogs_list"),
    path("create_blog", BlogCreateView.as_view(), name="create_blog"),
    path("edit/<int:pk>", BlogUpdateView.as_view(), name="edit"),
    path("view/<int:pk>", BlogDetailView.as_view(), name="view"),
    path("delete/<int:pk>", BlogDeleteView.as_view(), name="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

import mailing

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
]

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import Homepage, ClientCreateView, ClientListView, ClientDetailView, ClientUpdateView, \
    ClientDeleteView, MessageListView, MessageCreateView, MessageDetailView, MessageUpdateView, MessageDeleteView, \
    NewsletterCreateView, NewsletterUpdateView, NewsletterListView, NewsletterDetailView, NewsletterDeleteView, \
    LogsListView

app_name = MailingConfig.name

urlpatterns = [
    path("", cache_page(60)(Homepage.as_view()), name="home"),
    path("client_list/", ClientListView.as_view(), name="client_list"),
    path("create_client/", ClientCreateView.as_view(), name="create_client"),
    path("view_client/<int:pk>", ClientDetailView.as_view(), name="view_client"),
    path("edit_client/<int:pk>", ClientUpdateView.as_view(), name="edit_client"),
    path("delete_client/<int:pk>", ClientDeleteView.as_view(), name="delete_client"),

    path("message/list", MessageListView.as_view(), name="list_message"),
    path("message/create", MessageCreateView.as_view(), name="create_message"),
    path("message/view/<int:pk>", MessageDetailView.as_view(), name="view_message"),
    path("message/edit/<int:pk>", MessageUpdateView.as_view(), name="edit_message"),
    path("message/delete/<int:pk>", MessageDeleteView.as_view(), name="delete_message"),

    path("newsletter/create", NewsletterCreateView.as_view(), name="create_newsletter"),
    path("newsletter/edit/<int:pk>", NewsletterUpdateView.as_view(), name="edit_newsletter"),
    path("newsletter/list", NewsletterListView.as_view(), name="list_newsletter"),
    path("newsletter/view/<int:pk>", NewsletterDetailView.as_view(), name="view_newsletter"),
    path("newsletter/delete/<int:pk>", NewsletterDeleteView.as_view(), name="delete_newsletter"),

    path('logs/', LogsListView.as_view(), name='logs_list'),
]

mailing/models.py
from django.db import models

from users.models import User


class Client(models.Model):
    email = models.EmailField(verbose_name="Почта", unique=True)
    full_name = models.CharField(max_length=100, verbose_name="ФИО")
    comment = models.TextField(verbose_name="Комментарий", blank=True, null=True)

    owner = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name="Владелец", null=True, blank=True)

    def __str__(self):
        return f"{self.full_name} : {self.email}"

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"


class Message(models.Model):
    subject = models.CharField(max_length=50, verbose_name="Тема письма")
    body = models.TextField(verbose_name="Тело письма")

    owner = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name="Владелец", null=True, blank=True)

    def __str__(self):
        return f"{self.subject}"

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"


class Newsletter(models.Model):
    daily = "раз в день"
    weekly = "раз в неделю"
    monthly = "раз в месяц"
    Periodicity = [(daily, "раз в день"), (weekly, "раз в неделю"), (monthly, "раз в месяц")]

    finished = "завершена"
    created = "создана"
    launched = "запущена"
    Status = [(finished, "завершена"), (created, "создана"), (launched, "запущена")]

    start_time = models.DateTimeField(verbose_name="Время начала отправки рассылки")
    end_time = models.DateTimeField(verbose_name="Время окончания отправки рассылки")
    status = models.CharField(max_length=20, verbose_name="Статус рассылки", choices=Status, default=created)
    periodicity = models.CharField(max_length=20, verbose_name="Переодичность рассылки", choices=Periodicity)

    client = models.ManyToManyField(Client, verbose_name="Клиент", blank=True, null=True)
    message = models.ForeignKey(Message, verbose_name="Сообщение", on_delete=models.CASCADE, blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name="Владелец", null=True, blank=True)

    def __str__(self):
        return f"Рассылка {self.start_time} - {self.end_time}, {self.status}, {self.periodicity}"

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        permissions = [
            ('change_status', 'Can change newsletters status'),
        ]


class Logs(models.Model):
    attempt = models.BooleanField(verbose_name="Статус попытки")
    attempt_time = models.DateTimeField(verbose_name="Дата и время последней операции")
    response = models.CharField(max_length=100, verbose_name="Ответ сервера", null=True, blank=True)

    client = models.ForeignKey(Client, on_delete=models.SET_NULL, verbose_name="Клиент", null=True)
    newsletter = models.ForeignKey(Newsletter, verbose_name="Рассылка", null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f"Попытка от {self.attempt_time}, статус: {self.attempt}, ответ:{self.response}"

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = "Логи"

mailing/forms.py
from django.forms import ModelForm

from mailing.models import Client, Message, Newsletter


class ClientForm(ModelForm):
    class Meta:
        model = Client
        fields = ("full_name", "email", "comment",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = 'form-control'


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ("subject", "body",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = 'form-control'


class NewsletterForm(MessageForm):
    class Meta:
        model = Newsletter
        fields = ("start_time", "end_time", "status", "periodicity", "client", "message")

mailing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView, UpdateView, DetailView, DeleteView

from mailing.forms import ClientForm, MessageForm, NewsletterForm
from mailing.models import Client, Message, Newsletter, Logs


class Homepage(TemplateView):
    template_name = "mailing/base.html"


class ClientCreateView(CreateView, LoginRequiredMixin):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("mailing:client_list")
    login_url = 'users:login'

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class ClientListView(ListView, LoginRequiredMixin):
    model = Client
    success_url = reverse_lazy("mailing:client_list")
    login_url = 'users:login'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(id=self.kwargs.get('pk'))
        if not self.request.user.is_staff:
            queryset = queryset.filter(owner=self.request.user)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['clients_list'] = Client.objects.all()
        return context_data


class ClientUpdateView(UpdateView, LoginRequiredMixin):
    model = Client
    fields = ("full_name", "email", "comment",)
    success_url = reverse_lazy("mailing:client_list")
    login_url = "users:login"

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner == self.request.user or self.request.user.is_superuser:
            return self.object
        else:
            return Http404


class ClientDetailView(DetailView, LoginRequiredMixin):
    model = Client
    login_url = "users:login"


class ClientDeleteView(DeleteView, LoginRequiredMixin):
    model = Client
    success_url = reverse_lazy("mailing:client_list")
    login_url = "users:login"


class MessageCreateView(LoginRequiredMixin,CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailing:list_message")
    login_url = "users:login"

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class MessageUpdateView(UpdateView, LoginRequiredMixin):
    model = Message
    fields = ("subject", "body",)
    success_url = reverse_lazy("mailing:list_message")
    login_url = "users:login"

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404
        return self.object


class MessageListView(ListView, LoginRequiredMixin):
    model = Message
    success_url = reverse_lazy("mailing:list_message")
    login_url = "users:login"

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data["message_list"] = Message.objects.all()
        return context_data


class MessageDetailView(DetailView):
    model = Message


class MessageDeleteView(DeleteView, LoginRequiredMixin):
    model = Message
    success_url = reverse_lazy("mailing:list_message")
    login_url = "users:login"


class NewsletterCreateView(CreateView, LoginRequiredMixin):
    model = Newsletter
    form_class = NewsletterForm
    success_url = reverse_lazy("mailing:list_newsletter")
    login_url = "users:login"

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class NewsletterUpdateView(UpdateView, LoginRequiredMixin):
    model = Newsletter
    fields = ("start_time", "end_time", "periodicity", "status", "client", "message")
    success_url = reverse_lazy("mailing:list_newsletter")
    login_url = "users:login"

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner == self.request.user or self.request.user.is_superuser:
            return self.object
        else:
            raise Http404


class NewsletterListView(ListView, LoginRequiredMixin):
    model = Newsletter
    success_url = reverse_lazy("mailing:list_newsletter")
    login_url = "users:login"

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data["newsletter_list"] = Newsletter.objects.all()
        unique_clients = Client.objects.all().count()
        context_data["clients"] = unique_clients
        return context_data

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(id=self.kwargs.get('pk'))
        if not self.request.user.is_staff:
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class NewsletterDetailView(DetailView):
    model = Newsletter

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(id=self.kwargs.get("pk"))
        if not self.request.user.is_staff:
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class NewsletterDeleteView(DeleteView, LoginRequiredMixin):
    model = Newsletter
    success_url = reverse_lazy("mailing:list_newsletter")
    login_url = 'users:login'


class LogsListView(LoginRequiredMixin,ListView):
    model = Logs
    success_url = reverse_lazy('mailing:logs_list')
    login_url = 'users:login'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['total'] = Logs.objects.all()
        context_data['total_count'] = Logs.objects.all().count()
        context_data['successful_count'] = Logs.objects.filter(attempt=True).count()
        context_data['unsuccessful_count'] = Logs.objects.filter(attempt=False).count()
        return context_data

mailing/templates/mailing/base.html
{% load static %}

<html lang="en" data-bs-theme="auto" xmlns:blog="http://www.w3.org/1999/xhtml">
  <head><script src="{% static 'js/color-modes.js' %}"></script>
    <title>SkyService</title>
    <link rel="stylesheet" href="{% static 'css/css@3.css' %}">

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="{% static 'css/pricing.css' %}" rel="stylesheet">
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    {% include 'includes/main_menu.html' %}


  {% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Сервис рассылок</h1>
        <p class="lead">Добро пожаловать ^_^</p>
    </div>
    <div class="col-12 mb-5">
      <a href="{% url 'mailing:client_list' %}" class="btn btn-outline-primary">Список клиентов</a>
      <a href="{% url 'mailing:list_message' %}" class="btn btn-outline-primary">Список сообщений</a>
      <a href="{% url 'mailing:list_newsletter' %}" class="btn btn-outline-primary">Список рассылок</a>
    </div>
    <div class="card-body">
      <caption><h2>Записи в блогах</h2></caption>
      <table class="table table-striped">
          <tr>
            <th>Название блога</th>
            <th>Описание блога</th>
            <th>Дата публикации</th>
            <th>Ссылка на блог</th>
          </tr>
         {% for article in filtred_list %}
          <tr>
              <td>{{ article.title }}</td>
              <td>{{ article.description }}</td>
              <td>{{ article.published_date }}</td>
              <td><a href="{% url 'blog:view' %} article.pk "> Перейти к блогу</a></td>
          </tr>
         {% endfor %}
      </table>
    </div>
  {% endblock  %}
</div>
<script src="{% static 'js/bundle.min.js' %}" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    </body>
</html>

mailing/templates/mailing/client_detail.html
{% extends 'mailing/base.html' %}
{% load static %}

<!DOCTYPE html>
{% block icon %}
    <title>Добавить клиента</title>
{% endblock %}

</head>
<body>

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис рассылок</h1>
    <p class="lead">Ф.И.О клиента: {{ client.full_name | title }}</p>
</div>
  <div class="container">
    <div class="row">
         <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <div class="card-body">
              <span class="text-muted">Почта клиента: {{ client.email }}</span><br>
              <span class="text-muted">Комментарий: {{ client.comment }}</span>
            </div>
            <div class="card-footer">
              <a class="btn btn-link" href="{% url 'mailing:edit_client' client.pk%}">Изменить</a>
              <a class="btn btn-link" href="{% url 'mailing:delete_client' client.pk%}">Удалить</a>
            </div>
          </div>
        </div>
    </div>
  </div>
{% endblock %}


</body>
</html>

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}
{% load static %}

<!DOCTYPE html>
{% block icon %}
    <title>Список клиентов</title>
{% endblock %}

</head>
<body>

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Сервис рассылок</h1>
        <p class="lead">Добро пожаловать</p>
    </div>

  <main>
    {% for client in clients_list %}
      {% if user.is_superuser or client.owner == request.user or perms.mailing.view_client%}
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
          <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
              <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Ф.И.О клиента: {{ client.full_name | title }}</h4>
              </div>
              <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                  <li>Почта клиента: {{ client.email }}</li>
                </ul>
                <a type="button" href="{% url 'mailing:view_client' client.pk %}" class="w-100 btn btn-lg btn-primary">Информация</a>
                <a type="button" href="{% url 'mailing:edit_client' client.pk %}" class="w-100 btn btn-lg btn-primary">Изменить</a>
                <a type="button" href="{% url 'mailing:delete_client' client.pk %}" class="w-100 btn btn-lg btn-primary">Удалить</a>
              </div>
            </div>
          </div>
        </div>
      {% endif %}
    {% endfor %}
  </main>
   <div class="col-12 mb-5">
      <a href="{% url 'mailing:create_client' %}" class="btn btn-outline-primary">Добавить клиента</a>
   </div>
{% endblock %}


</body>
</html>

mailing/templates/mailing/logs_list.html
{% extends 'mailing/base.html' %}
{% load static %}


<html lang="en">
<head>

{% block icon %}
    <title>Список рассылок</title>
{% endblock %}

</head>
<body>


{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Статистика рассылок</h1>
    </div>
    <div class="col-12 mb-5">
      <p>Общее количество рассылок: {{total_count}}</p>
      <p>Общее количество успешных рассылок: {{successful_count}}</p>
      <p>Общее количество неуспешных рассылок: {{unsuccessful_count}}</p>
    </div>
{% endblock %}

</body>
</html>

mailing/templates/mailing/message_detail.html
{% extends 'mailing/base.html' %}
{% load static %}

<!DOCTYPE html>
{% block icon %}
    <title>Информация о сообщении</title>
{% endblock %}

</head>
<body>

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис рассылок</h1>
    <p class="lead">Тема письма: {{ message.subject| title }} </p>
</div>
  <div class="container">
    <div class="row">
         <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <div class="card-body">
              <span class="text-muted">Тело письма: {{ message.body }}</span><br>
            </div>
            <div class="card-footer">
              {% if perms.mailing.change_message or user.is_superuser or message.owner == request.user %}
                <a class="btn btn-link" href="{% url 'mailing:edit_message' message.pk%}">Изменить</a>
              {% endif %}
              {% if user.is_superuser or newsletter.owner == request.user or message.owner == request.user %}
                <a class="btn btn-link" href="{% url 'mailing:delete_message' message.pk%}">Удалить</a>
              {% endif %}
            </div>
          </div>
        </div>
    </div>
  </div>
{% endblock %}


</body>
</html>

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html' %}
{% load static %}

<!DOCTYPE html>
{% block icon %}
    <title>Список писем</title>
{% endblock %}

</head>
<body>

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Сервис рассылок</h1>
        <p class="lead">Добро пожаловать ^_^</p>
    </div>

  <main>
    {% for message in message_list %}
      {% if user.is_superuser or message.owner == request.user %}
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
          <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
              <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Тема письма: {{ message.subject }}</h4>
              </div>
              <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                  <li>Тело письма: {{ message.body }}</li>
                </ul>
                <a type="button" href="{% url 'mailing:view_message' message.pk%}" class="w-100 btn btn-lg btn-primary">Информация</a>
                {% if perms.mailing.change_message or user.is_superuser or message.owner == request.user %}
                    <a type="button" href="{% url 'mailing:edit_message' message.pk%}" class="w-100 btn btn-lg btn-primary">Изменить</a>
                {% endif %}
                {% if user.is_superuser or newsletter.owner == request.user or message.owner == request.user %}
                    <a type="button" href="{% url 'mailing:delete_message' message.pk%}" class="w-100 btn btn-lg btn-primary">Удалить</a>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      {% endif %}
    {% endfor %}
  </main>
   <div class="col-12 mb-5">
      <a href="{% url 'mailing:create_message' %}" class="btn btn-outline-primary">Добавить Сообщение</a>
   </div>
{% endblock %}


</body>
</html>

mailing/templates/mailing/newsletter_detail.html
 {% extends 'mailing/base.html' %}
{% load static %}

<!DOCTYPE html>
{% block icon %}
    <title>Информация о рассылки</title>
{% endblock %}

</head>
<body>

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис рассылок</h1>
</div>
  <div class="container">
    <div class="row">
         <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <div class="card-body">
                {% for item in newsletter.client.all %}
                   <span class="text-muted">Ф.И.О клиента: {{ item.full_name }}</span><br>
                   <span class="text-muted">Почта клиента: {{ item.email }}</span><br>
                {% endfor %}
                {% for i in newsletter.message.all %}
                    <h4 class="my-0 fw-normal">Тема письма: {{ i.subject }} </h4>
                {% endfor %}
            </div>
            <div class="card-footer">
              {% if newsletter.owner == request.user or user.is_superuser or perms.mailing.change_newsletter%}
                <a class="btn btn-link" href="{% url 'mailing:edit_newsletter' newsletter.pk%}">Изменить</a>
              {% endif %}
              {% if user.is_superuser or newsletter.owner == request.user or perms.mailing.delete_newsletter%}
                <a class="btn btn-link" href="{% url 'mailing:delete_newsletter' newsletter.pk%}">Удалить</a>
              {% endif %}
            </div>
          </div>
        </div>
    </div>
  </div>
{% endblock %}


</body>
</html>

mailing/templates/mailing/newsletter_list.html
{% extends 'mailing/base.html' %}
{% load static %}

<!DOCTYPE html>
{% block icon %}
    <title>Список писем</title>
{% endblock %}

</head>
<body>

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Сервис рассылок</h1>
        <p class="lead">Добро пожаловать ^_^</p>
        <p class="lead">Количество уникальных клиентов для рассылок : {{ clients }}</p>
    </div>

  <main>
    {% for newsletter in newsletter_list %}
      {% if user.is_superuser or newsletter.owner == request.user or perms.mailing.view_newsletter%}
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
          <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
              <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Время рассылки: {{ newsletter.start_time }} - {{ newsletter.end_time }} </h4>
              </div>
              <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                  <li>Периодичность: {{ newsletter.periodicity }}</li>
                  <li>Статус: {{ newsletter.status }}</li>
                  <li>Тема письма: {{ newsletter.message }}</li>
                </ul>
                <a type="button" href="{% url 'mailing:view_newsletter' newsletter.pk %}" class="w-100 btn btn-lg btn-primary">Информация</a>
                {% if newsletter.owner == request.user or user.is_superuser or perms.mailing.change_newsletter %}
                    <a type="button" href="{% url 'mailing:edit_newsletter' newsletter.pk %}" class="w-100 btn btn-lg btn-primary">Изменить</a>
                {% endif %}
                {% if user.is_superuser or newsletter.owner == request.user or perms.mailing.delete_newsletter%}
                    <a type="button" href="{% url 'mailing:delete_newsletter' newsletter.pk %}" class="w-100 btn btn-lg btn-primary">Удалить</a>
                {% endif %}
              </div>
            </div>
          </div>
      {% endif %}
        </div>
    {% endfor %}
  </main>
   <div class="col-12 mb-5">
      <a href="{% url 'mailing:create_newsletter' %}" class="btn btn-outline-primary">Добавить Рассылку</a>
   </div>
{% endblock %}


</body>
</html>